# Generated by Django 3.0.5 on 2020-05-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkedout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='topping',
            field=models.CharField(default='', max_length=250),
        ),
    ]
